In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('/content/drive/MyDrive/Online Retail.xlsx')

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [6]:
duplicate_count = df.duplicated().sum()

In [7]:
duplicate_count

np.int64(5268)

In [8]:
missing_values = df.isna().sum()
missing_values

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df = df.drop_duplicates()

In [10]:
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(0)

In [12]:
df = df.dropna(subset=['CustomerID'])

In [13]:
missing_values = df.isna().sum()
missing_values

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [14]:
df['CustomerID'] = df['CustomerID'].astype(int)

In [15]:
len(df)

401604

In [16]:
(df['Quantity'] <= 0).sum()

np.int64(8872)

In [18]:
(df['UnitPrice'] <= 0).sum()

np.int64(40)

In [19]:
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

In [20]:
(df['Quantity'] <= 0).sum()

np.int64(0)

In [21]:
(df['UnitPrice'] <= 0).sum()

np.int64(0)

In [23]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

/tmp/ipykernel_677/114513391.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

In [24]:
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)].copy()
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

In [25]:
len(df)

392692

In [26]:
import re

In [27]:
df['Description'] = df['Description'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', str(x)).strip() if pd.notna(x) else x)
df['StockCode'] = df['StockCode'].astype(str).str.replace(r'[^0-9]', '', regex=True)
df = df[df['StockCode'] != ''].copy()

In [28]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123,WHITE HANGING HEART TLIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029,RED WOOLLY HOTTIE WHITE HEART,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [30]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Clean_Data'] = df['InvoiceDate'].dt.date
df['Purchase_Hour'] = df['InvoiceDate'].dt.hour
df = df.drop(columns=['InvoiceDate']).copy()

In [31]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalAmount,Clean_Data,Purchase_Hour
0,536365,85123,WHITE HANGING HEART TLIGHT HOLDER,6,2.55,17850,United Kingdom,15.30,2010-12-01,8
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,20.34,2010-12-01,8
2,536365,84406,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850,United Kingdom,22.00,2010-12-01,8
3,536365,84029,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850,United Kingdom,20.34,2010-12-01,8
4,536365,84029,RED WOOLLY HOTTIE WHITE HEART,6,3.39,17850,United Kingdom,20.34,2010-12-01,8
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,7.65,17850,United Kingdom,15.30,2010-12-01,8
6,536365,21730,GLASS STAR FROSTED TLIGHT HOLDER,6,4.25,17850,United Kingdom,25.50,2010-12-01,8
7,536366,22633,HAND WARMER UNION JACK,6,1.85,17850,United Kingdom,11.10,2010-12-01,8
8,536366,22632,HAND WARMER RED POLKA DOT,6,1.85,17850,United Kingdom,11.10,2010-12-01,8
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,13047,United Kingdom,54.08,2010-12-01,8

In [32]:
df.to_csv('/content/drive/MyDrive/online_retail_perfect_clean.csv', index=False, encoding='utf-8-sig')